# Generated by Django 4.2.2 on 2023-06-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nmc',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
