# Generated by Django 4.2.2 on 2023-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_nmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='doc_image'),
        ),
    ]
